services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    user: "${UID}:${GID}"
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../../apps/api:/app

volumes:
  dbdata:
