"""create state and city

Revision ID: 07dd14444205
Revises: d4faee3fc3ab
Create Date: 2026-02-27 18:11:09.697022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dd14444205'
down_revision: Union[str, None] = 'd4faee3fc3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'country_id', 'code', name='uq_state_tenant_country_code'),
    sa.UniqueConstraint('tenant_id', 'country_id', 'name', name='uq_state_tenant_country_name')
    )
    op.create_index(op.f('ix_state_country_id'), 'state', ['country_id'], unique=False)
    op.create_index('ix_state_tenant_country', 'state', ['tenant_id', 'country_id'], unique=False)
    op.create_index(op.f('ix_state_tenant_id'), 'state', ['tenant_id'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ibge_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'state_id', 'name', name='uq_city_tenant_state_name')
    )
    op.create_index(op.f('ix_city_state_id'), 'city', ['state_id'], unique=False)
    op.create_index(op.f('ix_city_tenant_id'), 'city', ['tenant_id'], unique=False)
    op.create_index('ix_city_tenant_state', 'city', ['tenant_id', 'state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_city_tenant_state', table_name='city')
    op.drop_index(op.f('ix_city_tenant_id'), table_name='city')
    op.drop_index(op.f('ix_city_state_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_state_tenant_id'), table_name='state')
    op.drop_index('ix_state_tenant_country', table_name='state')
    op.drop_index(op.f('ix_state_country_id'), table_name='state')
    op.drop_table('state')
    # ### end Alembic commands ###
